# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QLabel, QSpacerItem, QSizePolicy
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import QTimer, QTime, Qt
from PyQt5.QtMultimedia import QSound


class Tongue_test_Window(QDialog):
    def __init__(self):
        super(Tongue_test_Window, self).__init__()
        self.setWindowTitle("舌动伪迹采集")
        self.resize(2600,1600)

        # 创建显示倒计时的 QLabel
        layout = QtWidgets.QVBoxLayout(self)  # 创建一个 QVBoxLayout 布局管理器
        self.timer_label = QLabel(self)
        self.timer_label.setAlignment(Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(35)  # 设置字体大小
        self.timer_label.setFont(font)
        layout.addWidget(self.timer_label, alignment=Qt.AlignCenter)

        # 创建定时器
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.read)

    def reminder_3times(self):
        self.remind_count = 3
        self.reminder()

    def reminder(self):
        self.num_text = 8
        self.text_list = ["跟读以下短语：", "啰里啰唆", "来去匆匆", "了无牵挂", "流连忘返", "乐在其中", "来龙去脉", "黎明破晓"]
        self.sound_list = ["跟读.wav", "啰嗦.wav", "来去.wav", "牵挂.wav", "流连忘返.wav", "乐在.wav", "来龙.wav", "黎明.wav"]
        self.list_count = 0
        self.timer.start(4000)

    def read(self):
        if self.num_text != 0:
            self.timer_label.setText(self.text_list[self.list_count])
            QSound.play(self.sound_list[self.list_count])
            self.play_alarm()
            self.list_count += 1
            self.num_text -= 1
        else:
            self.play_alarm()
            self.timer.stop()
            if self.remind_count != 0:
                self.reminder()
                self.remind_count -= 1
            else:
                self.play_alarm()
                QSound.play("结束.wav")
                self.timer_label.setText("舌动测试结束！")


    def play_alarm(self):
        # 播放声音，确保你有这个文件
        QSound.play("alert.wav")  # 音频文件路径


